services:
  prod-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  prod-nest:
    image: nest:1.0
    build: .
    ports:
      - 3000:3000
    depends_on:
      prod-db:
        condition: service_healthy
        restart: true
    command: sh -c "
      npx prisma migrate deploy
      && npm run start:prod
      "
